#!/bin/bash

stedgeai generate --no-inputs-allocation --no-outputs-allocation --model best_PerChannel_quant_calib_nchw_f32_npz_1.onnx --target stm32n6 --st-neural-art default@user_neuralart.json

# 如果兼容头不存在，则生成一份（某些环境下不会随 STAI 产物自动生成）。
if [[ ! -f "${COMPAT_HEADER}" ]]; then
  cat > "${COMPAT_HEADER}" <<'EOF'
/**
 * Compatibility helpers for autogenerated network.c files.
 *
 * Newer STAI generators (>= 2.2) emit the flag `EpochBlock_Flags_blob_encrypted`
 * for encrypted external blobs. Older ll_aton headers (used in this project)
 * do not define this enum value, which causes a build failure. Defining it to
 * `EpochBlock_Flags_blob` keeps the code compatible without changing the
 * runtime behaviour (encrypted blobs are not used in this project).
 */
#ifndef EPOCH_BLOCK_FLAGS_COMPAT_H
#define EPOCH_BLOCK_FLAGS_COMPAT_H

#ifndef EpochBlock_Flags_blob_encrypted
#define EpochBlock_Flags_blob_encrypted EpochBlock_Flags_blob
#endif

#endif /* EPOCH_BLOCK_FLAGS_COMPAT_H */
EOF
fi



cp st_ai_output/network_ecblobs.h .
cp st_ai_output/network.c .
cp st_ai_output/network_atonbuf.xSPI2.raw network_data.xSPI2.bin
arm-none-eabi-objcopy -I binary network_data.xSPI2.bin --change-addresses 0x70200000 -O ihex ../Binary/network-data.hex
# Ensure compatibility with older ll_aton headers that do not define
# EpochBlock_Flags_blob_encrypted (added in newer STAI releases).
python - <<'PY'
from pathlib import Path

net = Path('network.c')
compat_include = '#include "network_epoch_flags_compat.h"\n'
if net.exists():
    text = net.read_text()
    if compat_include.strip() not in text:
        anchor = '#include "ecloader.h"\n'
        if anchor in text:
            text = text.replace(anchor, anchor + compat_include)
        else:
            text = compat_include + text
        net.write_text(text)
PY